name: Cyberk's Blog
title: Cyberk's Blog
description: 需想象西西弗斯是幸福的

url: ""
baseurl: ""
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - jekyll.out.log
  - jekyll.err.log
