name: cyberk's Blog
title: cyberk's Blog
description: 技术文档与代码笔记

url: ""
baseurl: ""
permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - jekyll.out.log
  - jekyll.err.log
